Market/Controllers/InvoiceController.cs
using Market.Models;
using Market.Models.Repositories;
using Market.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Market.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly IInvoiceRepository _invoiceRepository;

        public InvoiceController(IInvoiceRepository invoceRepository)
        {
            _invoiceRepository = invoceRepository;
        }
        public IActionResult Index()
        {
            var products = _invoiceRepository.List();
            return View(products);
        }
        [HttpGet]
        public ActionResult Create(int invoiceId)
        {
            var model = new ProductViewModel();
            model.InvoiceId = invoiceId;
            if (invoiceId > 0)
            {
                model.ProductList = _invoiceRepository.GetProductListByInvoiceId(invoiceId);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel product)
        {
            string userId = HttpContext.User.Claims.FirstOrDefault(x => x.Type ==ApplicationClaimTypes.UserId)!.Value;
            var invoiceId = _invoiceRepository.Add(product,int.Parse(userId));
            return RedirectToAction(nameof(Create), new { InvoiceId = invoiceId });
        }
    }
}

Market/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace Market.Controllers
{
    public class LanguageController : Controller
    {
        private readonly IStringLocalizer<LanguageController> _localizer;

        public LanguageController(IStringLocalizer<LanguageController> localizer)
        {
            _localizer = localizer;
        }
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

Market/Controllers/UserController.cs
using Market.Models;
using Market.Models.Repositories;
using Market.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Market.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;

        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            var users = _userRepository.List();
            return View(users);
        }
        [HttpPost]
        public IActionResult AddUserOfList(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                _userRepository.Add(userViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(userViewModel);
        }

        public ActionResult EditUser(int id)
        {
            var user = _userRepository.GetOne(id);
            return View(user);
        }

        [HttpPost]
        public IActionResult EditUser(int id, UserViewModel user)
        {

            _userRepository.Update(id, user);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            string isAdmin = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ApplicationClaimTypes.IsAdmin)!.Value;
            if (Convert.ToBoolean(isAdmin))
            {
                _userRepository.Delete(id);
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Search(string term)
        {
            var result = _userRepository.Search(term);
            return View("Index", result);
        }

    }
}

Market/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Market</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Market.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">@localizer["Market"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">@localizer["Main"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="Index">@localizer["Invoices"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">@localizer["Registration"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">@localizer["Login"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">@localizer["Logout"]</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-action="Search" asp-controller="User">
                        <input class="form-control mr-sm-2" name="term" type="search" placeholder="@localizer["Search Of User"]" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">@localizer["Search"]</button>
                    </form>
                    <div>
                        <partial name="_SelectLanguagePartial" />
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - @localizer["Market"] - <a asp-area="" asp-page="/Privacy">@localizer["Privacy"]</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Market/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> locOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedUICultures!
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" method="POST" asp-controller="Language" asp-action="SetLanguage"
          asp-route-returnUrl="@returnUrl">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture!.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>